export const QUESTIONS_PER_SESSION = 8;

const OPTION_KEYS = ["A", "B", "C", "D"];
const QUADRANT_KEYS = ["ll", "lr", "rl", "rr"];

function makePack(options) {
  return options.map((option, index) => ({
    optionKey: OPTION_KEYS[index],
    quadrant: QUADRANT_KEYS[index],
    text: option.text,
    tags: option.tags || {},
  }));
}

function quadrantScores(theme, quadrant, tags) {
  const [axis1, axis2] = theme.axes;
  const scores = {
    [quadrant[0] === "l" ? axis1.leftKey : axis1.rightKey]: 2,
    [quadrant[1] === "l" ? axis2.leftKey : axis2.rightKey]: 2,
  };

  return {
    quadrant,
    scores,
    tags,
  };
}

function buildProfiles(theme) {
  const [axis1, axis2] = theme.axes;

  function pole(axis, side) {
    return side === "l"
      ? {
          key: axis.leftKey,
          label: axis.leftLabel,
          short: axis.leftShort,
          strength: axis.leftStrength,
          blindSpot: axis.leftBlindSpot,
          growth: axis.leftGrowth,
          oppositeShort: axis.rightShort,
        }
      : {
          key: axis.rightKey,
          label: axis.rightLabel,
          short: axis.rightShort,
          strength: axis.rightStrength,
          blindSpot: axis.rightBlindSpot,
          growth: axis.rightGrowth,
          oppositeShort: axis.leftShort,
        };
  }

  function quadrantProfile(side1, side2, key, title) {
    const first = pole(axis1, side1);
    const second = pole(axis2, side2);

    return {
      profileKey: key,
      title,
      summary: `在${theme.domain}這件事上，你通常會先用${first.label}讀懂現場，再用${second.label}決定自己的節奏。${theme.surpriseLine}`,
      strengths: [
        `你常能${first.strength}。`,
        `你也擅長${second.strength}。`,
        `遇到曖昧或混亂時，你比較容易找到一種對自己有交代的做法。`,
      ],
      blindSpots: [
        `當你太依賴${first.short}時，${first.blindSpot}。`,
        `當壓力升高時，${second.blindSpot}。`,
        `你有時會把另一種同樣重要的需求，留到太後面才處理。`,
      ],
      growthSuggestions: [
        `保留你的${first.short}優勢，同時刻意借一點${first.oppositeShort}的視角。`,
        `在做出反應前，留十秒問自己：我現在要的是安全感，還是真正適合我的方向？`,
        `替${second.short}留一點鬆動空間，通常會讓你更像自己，也更有餘裕。`,
      ],
      basePrompt: `這個人在人格測驗主題「${theme.title}」中呈現 ${first.label} 與 ${second.label} 的組合。請用溫暖、像被理解的口吻補上一段 80 到 120 字的鏡像式洞察，避免診斷感。`,
      matchingRules: {
        kind: "quadrant",
        axis1: side1 === "l" ? axis1.leftKey : axis1.rightKey,
        axis2: side2 === "l" ? axis2.leftKey : axis2.rightKey,
      },
    };
  }

  return [
    quadrantProfile("l", "l", "quadrant_ll", theme.profileTitles.quadrant_ll),
    quadrantProfile("l", "r", "quadrant_lr", theme.profileTitles.quadrant_lr),
    quadrantProfile("r", "l", "quadrant_rl", theme.profileTitles.quadrant_rl),
    quadrantProfile("r", "r", "quadrant_rr", theme.profileTitles.quadrant_rr),
    {
      profileKey: "balanced_integration",
      title: theme.profileTitles.balanced_integration,
      summary: `你有能力用不只一套本能生活。面對${theme.domain}，你能在${axis1.leftLabel}與${axis1.rightLabel}之間切換，也能在${axis2.leftLabel}與${axis2.rightLabel}之間找到自己的比例。`,
      strengths: [
        `你比多數人更能同時看見兩種需求，不急著把自己塞進單一標籤。`,
        `你能在穩定與流動、理性與感受之間找到彼此合作的方法。`,
        `你的成熟感來自懂得辨認情緒，也知道什麼時候該換工具。`,
      ],
      blindSpots: [
        `因為你看得到很多面向，有時反而比較晚承認自己真正偏向哪裡。`,
        `你容易把「我都能理解」誤當成「我已經做出選擇」。`,
        `當情境很模糊時，你可能會先維持平衡，卻延後真正的行動。`,
      ],
      growthSuggestions: [
        `把平衡當作優勢，但不要讓平衡變成拖延表態的理由。`,
        `在重要時刻，先問自己：今天我最想保護的是什麼？`,
        `允許自己短暫偏向某一邊，因為清楚選擇有時比漂亮平衡更重要。`,
      ],
      basePrompt: `這個人在「${theme.title}」中呈現高度整合型結果。請寫一段 80 到 120 字的中文鏡像洞察，語氣溫柔、清晰、像被看懂。`,
      matchingRules: {
        kind: "balanced_integration",
      },
    },
    {
      profileKey: "balanced_bridge",
      title: theme.profileTitles.balanced_bridge,
      summary: `你有一條很穩的主軸，也在另一條主軸上保留彈性。這讓你在${theme.domain}裡，看起來既不僵硬，也不會完全被情境牽著走。`,
      strengths: [
        `你知道自己真正不能退讓的那一面，也知道哪裡可以變通。`,
        `比起死守風格，你更擅長把自己的狀態調到剛剛好。`,
        `你常能在不失去自己的前提下，跟情境做出合作。`,
      ],
      blindSpots: [
        `別人可能以為你什麼都能適應，卻看不到你其實也會累。`,
        `你有時會把彈性優先用來照顧場面，自己的需要也值得被排進來。`,
        `當那條穩定主軸被碰撞時，你的反應可能比平常更強。`,
      ],
      growthSuggestions: [
        `繼續保留你的調頻能力，但也替自己設一個不需要再撐的界線。`,
        `別只問自己能不能適應，也要問值不值得你適應。`,
        `在關鍵關係或選擇裡，把你的主軸說清楚，會比默默配合更輕鬆。`,
      ],
      basePrompt: `這個人在「${theme.title}」中呈現橋接型結果。請補一段 80 到 120 字的鏡像洞察，讓人感覺被理解但不被定型。`,
      matchingRules: {
        kind: "balanced_bridge",
      },
    },
    {
      profileKey: "tension_mirror",
      title: theme.profileTitles.tension_mirror,
      summary: `你的內在同時有兩套很有力量的需求在拉扯。你能感受到${theme.domain}裡彼此衝突的兩邊，所以常常比別人更細膩，也更容易內耗。`,
      strengths: [
        `你的感受很有層次，所以你也比很多人更能理解複雜的感受。`,
        `你對矛盾特別敏感，這讓你看得深，也不容易隨便自欺。`,
        `當你站穩之後，你會比單一路線的人更有厚度。`,
      ],
      blindSpots: [
        `因為每一邊都是真的，你可能會在選擇前先被自己的拉扯耗掉。`,
        `你容易把矛盾解讀成自己不夠成熟，其實那更像是兩個重要需求都在說話。`,
        `當壓力很大時，你可能同時想靠近又想退開，讓自己更困惑。`,
      ],
      growthSuggestions: [
        `先不要逼自己立刻統一，只要先替兩邊都取一個名字。`,
        `當你感到拉扯時，先分辨現在是害怕失去，還是害怕被困住。`,
        `給內在衝突一點文字和空間，通常會比較快看見路。`,
      ],
      basePrompt: `這個人在「${theme.title}」中呈現高拉扯、鏡像型結果。請寫一段 80 到 120 字的中文鏡像洞察，像在替他把混亂說成人話。`,
      matchingRules: {
        kind: "tension_mirror",
      },
    },
    {
      profileKey: "tension_pivot",
      title: theme.profileTitles.tension_pivot,
      summary: `你正在兩種重要需求之間找新的比例。這段調整代表你已經長到不能再只靠舊方法活著，所以在${theme.domain}上會特別有「明明知道，卻還在調整」的感覺。`,
      strengths: [
        `你開始能看見自己正在長出新的版本，不必再用非黑即白理解自己。`,
        `你對轉換時刻很敏感，所以也比較能捕捉真正的變化。`,
        `你正在替新的重心找位置，節奏會慢慢穩下來。`,
      ],
      blindSpots: [
        `轉換期很容易讓你誤會自己退步，實際上你只是還沒長出新節奏。`,
        `你可能一邊想往前，一邊又想維持熟悉感，於是卡在中間。`,
        `如果外界又急又吵，你會更難分辨哪個聲音是你自己的。`,
      ],
      growthSuggestions: [
        `把轉換期當成過程，不要急著把自己判成矛盾。`,
        `先選一個最想保護的核心，再讓其他變化慢慢跟上。`,
        `當你感覺自己卡住時，回頭看最近哪些事情其實已經不一樣了。`,
      ],
      basePrompt: `這個人在「${theme.title}」中呈現轉換期、樞紐型結果。請寫一段 80 到 120 字的鏡像洞察，讓人感覺被安放、被理解，避免分析感。`,
      matchingRules: {
        kind: "tension_pivot",
      },
    },
  ];
}

function buildQuestions(theme) {
  return theme.contexts.flatMap((context, contextIndex) =>
    theme.promptTemplates.map((template, templateIndex) => {
      const code = `${theme.code}-${String(contextIndex * theme.promptTemplates.length + templateIndex + 1).padStart(2, "0")}`;
      const prompt = template.replace("{context}", context);
      const pack = theme.packs[templateIndex];

      return {
        id: `${theme.slug}-${code.toLowerCase()}`,
        code,
        prompt,
        contextHint: context,
        sortOrder: contextIndex * theme.promptTemplates.length + templateIndex + 1,
        options: pack.map((option) => ({
          id: `${theme.slug}-${code.toLowerCase()}-${option.optionKey.toLowerCase()}`,
          optionKey: option.optionKey,
          text: option.text,
          traitWeights: quadrantScores(theme, option.quadrant, option.tags),
        })),
      };
    }),
  );
}

function buildTopic(theme) {
  const questions = buildQuestions(theme);
  const resultProfiles = buildProfiles(theme);

  return {
    slug: theme.slug,
    code: theme.code,
    icon: theme.icon,
    title: theme.title,
    shortTitle: theme.shortTitle,
    subtitle: theme.subtitle,
    description: theme.description,
    cardDescription: theme.cardDescription,
    heroCopy: theme.heroCopy,
    shareTitle: theme.shareTitle,
    shareDescription: theme.shareDescription,
    locale: "zh-TW",
    themeColor: theme.themeColor,
    themeColorSoft: theme.themeColorSoft,
    themeInk: theme.themeInk,
    themeGlow: theme.themeGlow,
    domain: theme.domain,
    axes: theme.axes,
    tagLabels: theme.tagLabels,
    questionPoolSize: questions.length,
    questionsPerSession: QUESTIONS_PER_SESSION,
    questions,
    resultProfiles,
  };
}

const THEME_BLUEPRINTS = [
  {
    slug: "personality-type",
    code: "PT",
    icon: "◎",
    title: "你的人格節奏偏向哪一型？",
    shortTitle: "人格節奏",
    subtitle: "你理解世界、安排自己的方式，比外向或內向更有層次。",
    description: "從日常安排、變動反應與第一直覺裡，看見你的個性骨架。",
    cardDescription: "看你怎麼安排、感受與應對變化。",
    heroCopy: "有些人先拆解，有些人先感受；有些人需要結構，有些人活在流動裡。這份測驗會照出你習慣怎麼跟世界對話。",
    shareTitle: "人格節奏心理測驗",
    shareDescription: "測出你理解世界與安排自己的心理節奏。",
    themeColor: "#a76d53",
    themeColorSoft: "#e7c2af",
    themeInk: "#241914",
    themeGlow: "rgba(167,109,83,0.28)",
    domain: "安排自己與理解世界",
    surpriseLine: "你有彈性，也有自己獨特的安心定義。",
    axes: [
      {
        key: "processing_style",
        leftKey: "analytical",
        leftLabel: "分析取向",
        leftShort: "分析",
        leftStrength: "把複雜狀況拆成可處理的部分",
        leftBlindSpot: "你可能會把感覺延後到太後面",
        leftGrowth: "在分析之前先承認自己的第一反應",
        rightKey: "intuitive",
        rightLabel: "直覺取向",
        rightShort: "直覺",
        rightStrength: "很快讀到氣氛與隱性方向",
        rightBlindSpot: "你有時會先跟著感覺走，再補理由",
        rightGrowth: "讓感覺成形後，再補一個現實檢查",
      },
      {
        key: "rhythm_style",
        leftKey: "structured",
        leftLabel: "有結構",
        leftShort: "結構",
        leftStrength: "替混亂建立穩定順序",
        leftBlindSpot: "你可能會對臨時變化太早緊繃",
        leftGrowth: "替計畫預留一點彈性空間",
        rightKey: "spontaneous",
        rightLabel: "即興流動",
        rightShort: "即興",
        rightStrength: "在變動裡保有活力與創意",
        rightBlindSpot: "你有時會把穩定感交給明天的自己",
        rightGrowth: "讓靈感有地方落地，感覺會更容易成為真實行動",
      },
    ],
    tagLabels: {
      grounded: "穩住節奏",
      curiosity: "好奇心",
      control_need: "掌控感",
      openness: "開放度",
      recovery: "回彈力",
      sensitivity: "敏感度",
    },
    profileTitles: {
      quadrant_ll: "冷靜佈局者",
      quadrant_lr: "感受型策展者",
      quadrant_rl: "即興拆解者",
      quadrant_rr: "流動探索者",
      balanced_integration: "雙頻整合者",
      balanced_bridge: "溫和調頻者",
      tension_mirror: "內在拔河者",
      tension_pivot: "轉速切換者",
    },
    promptTemplates: [
      "當{context}時，你最先冒出的反應通常比較像哪一種？",
      "遇到{context}這種情境，你多半會怎麼處理自己？",
      "如果{context}，你最可能先採取哪一步？",
      "在{context}的那一刻，真正推著你往前的通常是什麼？",
    ],
    contexts: [
      "行程突然被打亂",
      "要加入一個陌生的小圈子",
      "收到一個很模糊的新任務",
      "空出一整天沒有安排",
      "討論到一半方向突然改變",
      "腦中突然冒出一個讓你心動的新點子",
      "必須在兩個都不錯的選擇裡快速決定",
      "出門前直覺覺得哪裡怪怪的",
    ],
    packs: [
      makePack([
        { text: "我會先把變數分開看，弄清楚哪裡需要重排。", tags: { grounded: 1, control_need: 1 } },
        { text: "我會先穩住整體節奏，再跟著那個最有感覺的方向微調。", tags: { grounded: 1, openness: 1 } },
        { text: "我通常邊試邊看，先做出第一步，讓情況自己告訴我答案。", tags: { curiosity: 1, recovery: 1 } },
        { text: "我會順著當下的感受走，看看哪條路比較有生命力。", tags: { openness: 1, sensitivity: 1 } },
      ]),
      makePack([
        { text: "先把狀況講清楚，我心裡就會安定很多。", tags: { control_need: 1, grounded: 1 } },
        { text: "我會先幫自己留一個框，再看直覺想往哪裡靠。", tags: { grounded: 1, sensitivity: 1 } },
        { text: "我不太想先定義，通常會先讓自己動起來再說。", tags: { curiosity: 1, recovery: 1 } },
        { text: "我比較像在聽自己內在的風向，不會急著把它說死。", tags: { openness: 1, sensitivity: 1 } },
      ]),
      makePack([
        { text: "先列出關鍵條件與順序，確定不會亂掉。", tags: { grounded: 1, control_need: 1 } },
        { text: "先抓住大方向，再用感覺決定細節要留給哪裡。", tags: { grounded: 1, openness: 1 } },
        { text: "先做一個小測試，看看哪個版本比較有反應。", tags: { curiosity: 1, recovery: 1 } },
        { text: "先靠近那個讓我有畫面的選項，其他的之後再說。", tags: { openness: 1, sensitivity: 1 } },
      ]),
      makePack([
        { text: "被理解與可掌握感會讓我比較放心。", tags: { control_need: 1, grounded: 1 } },
        { text: "我想同時保留穩定感和心動感。", tags: { grounded: 1, sensitivity: 1 } },
        { text: "新鮮感和能立刻驗證的反應很吸引我。", tags: { curiosity: 1, recovery: 1 } },
        { text: "那種說不上來、但很對味的感覺會推著我走。", tags: { openness: 1, sensitivity: 1 } },
      ]),
    ],
  },
  {
    slug: "emotional-patterns",
    code: "EP",
    icon: "◔",
    title: "你的情緒慣性最像哪一種？",
    shortTitle: "情緒慣性",
    subtitle: "情緒有自己的大小、流向與保護方式。",
    description: "從情緒升起、停留與退場的方式，看見你如何照顧受傷的自己。",
    cardDescription: "看見你平常怎麼接住情緒、又怎麼被情緒帶走。",
    heroCopy: "有些人把情緒往內收，有些人需要說出來才呼吸得到空氣。這份測驗想照出你的情緒力量與運作方式。",
    shareTitle: "情緒慣性心理測驗",
    shareDescription: "測出你情緒升起時最常啟動的保護模式。",
    themeColor: "#9d668a",
    themeColorSoft: "#e3c4d9",
    themeInk: "#23161f",
    themeGlow: "rgba(157,102,138,0.25)",
    domain: "情緒升起、停留與退場",
    surpriseLine: "你的情緒很細緻，表達和保護感受的方式也很有層次。",
    axes: [
      {
        key: "emotion_expression",
        leftKey: "internalized",
        leftLabel: "內收處理",
        leftShort: "內收",
        leftStrength: "先在心裡整理自己的真實感受",
        leftBlindSpot: "外面的人可能看不見你其實已經很滿",
        leftGrowth: "在還能說清楚時，先吐露一點點真實",
        rightKey: "expressive",
        rightLabel: "外放表達",
        rightShort: "外放",
        rightStrength: "讓情緒有出口，不讓它悶成結",
        rightBlindSpot: "你有時會在情緒還沒落地前，就先把它丟向外面",
        rightGrowth: "先確認你要的是被懂，還是只是要把感受釋放掉",
      },
      {
        key: "emotion_regulation",
        leftKey: "self_soothing",
        leftLabel: "自我緩衝",
        leftShort: "自我緩衝",
        leftStrength: "替自己找回節奏，不急著反應",
        leftBlindSpot: "你可能太會自己吞，別人不知道該怎麼靠近你",
        leftGrowth: "練習把安靜照顧自己，和允許別人陪你，放在同一張地圖上",
        rightKey: "reactive",
        rightLabel: "即時反應",
        rightShort: "即時反應",
        rightStrength: "很誠實地反映當下的衝擊與感受",
        rightBlindSpot: "情緒來得快時，你可能會先被浪頭推著走",
        rightGrowth: "先替情緒命名，再決定要不要立刻回應",
      },
    ],
    tagLabels: {
      softness: "柔軟感",
      intensity: "情緒張力",
      tenderness: "被理解需求",
      privacy: "情緒隱私",
      release: "釋放需求",
      recovery: "情緒回彈",
    },
    profileTitles: {
      quadrant_ll: "安靜沉澱者",
      quadrant_lr: "壓抑爆點者",
      quadrant_rl: "坦率流動者",
      quadrant_rr: "情緒放電者",
      balanced_integration: "情緒整合者",
      balanced_bridge: "溫柔調節者",
      tension_mirror: "感受拉扯者",
      tension_pivot: "潮汐切換者",
    },
    promptTemplates: [
      "當{context}時，你的情緒第一波通常怎麼動？",
      "遇到{context}這種時刻，你多半怎麼跟自己的感受相處？",
      "如果{context}，你最容易先做哪件事？",
      "在{context}的那一刻，你真正最需要的是什麼？",
    ],
    contexts: [
      "朋友的一句話剛好刺到你",
      "工作臨時出包又沒人能接手",
      "半夜突然想起一段舊事",
      "收到一則讓你心冷一下的回覆",
      "一整天都很累，卻還要維持正常",
      "跟家人有點摩擦但說不清楚",
      "某個原本期待的安排突然落空",
      "情緒一下子湧上來，連你自己都措手不及",
    ],
    packs: [
      makePack([
        { text: "我通常先收回來，想弄清楚自己到底在難受什麼。", tags: { privacy: 1, softness: 1 } },
        { text: "我會先壓住表面，直到能安全地把感覺說出口。", tags: { privacy: 1, tenderness: 1 } },
        { text: "我很容易立刻讓情緒露出來，因為那一刻真的很真。", tags: { release: 1, intensity: 1 } },
        { text: "我的情緒會先衝出來，像身體比理智更早知道痛。", tags: { release: 1, intensity: 1 } },
      ]),
      makePack([
        { text: "我會先自己消化，等整理到一個程度再決定要不要說。", tags: { privacy: 1, recovery: 1 } },
        { text: "我想自己穩住，但其實也會偷偷期待有人看得懂。", tags: { tenderness: 1, recovery: 1 } },
        { text: "我需要把感覺講出來，講著講著才知道自己真正怎麼了。", tags: { release: 1, tenderness: 1 } },
        { text: "我通常會立刻有反應，不然那股情緒會把我卡住。", tags: { intensity: 1, release: 1 } },
      ]),
      makePack([
        { text: "先讓自己安靜下來，不急著對外說明。", tags: { recovery: 1, privacy: 1 } },
        { text: "先讓情緒不失控，再試著挑一個能被理解的出口。", tags: { recovery: 1, tenderness: 1 } },
        { text: "先找人講講，因為我需要讓感受有空氣。", tags: { release: 1, tenderness: 1 } },
        { text: "先回應那個瞬間，不然我會覺得自己被情緒淹掉。", tags: { intensity: 1, release: 1 } },
      ]),
      makePack([
        { text: "我需要一段不被打擾的時間，先陪自己。", tags: { softness: 1, privacy: 1 } },
        { text: "我需要有人看見我，但不要一下子逼我全說清楚。", tags: { tenderness: 1, privacy: 1 } },
        { text: "我需要情緒能被接住、被回應，也被好好重視。", tags: { tenderness: 1, release: 1 } },
        { text: "我需要立刻鬆掉那股張力，不然很難恢復理智。", tags: { intensity: 1, release: 1 } },
      ]),
    ],
  },
  {
    slug: "stress-response",
    code: "SR",
    icon: "△",
    title: "壓力來時，你最常啟動哪種反應？",
    shortTitle: "壓力反應",
    subtitle: "壓力來時，你會用自己的方式保住自己。",
    description: "從高壓時刻的第一反應，看見你的壓力生存策略。",
    cardDescription: "測出壓力一來時，你是撐住、切斷、對外、還是往內縮。",
    heroCopy: "每個人都有自己的壓力生存方式。有的人先動，有的人先凍住，有的人把力氣往內吞，有的人往外放。這些反應都在提醒你，系統正在努力求生。",
    shareTitle: "壓力反應心理測驗",
    shareDescription: "看見你在高壓場景下最常啟動的自保策略。",
    themeColor: "#6f7d96",
    themeColorSoft: "#c8d0e0",
    themeInk: "#151b24",
    themeGlow: "rgba(111,125,150,0.28)",
    domain: "高壓情境與求生反應",
    surpriseLine: "你的壓力模式帶著保護你的用意。",
    axes: [
      {
        key: "pressure_motion",
        leftKey: "proactive",
        leftLabel: "先動起來",
        leftShort: "先動",
        leftStrength: "在混亂中盡快找到可做的事",
        leftBlindSpot: "你有時會靠一直做來掩蓋自己其實已經很緊繃",
        leftGrowth: "行動前先確認自己正在照顧焦慮，也正在靠近真正需要處理的事",
        rightKey: "shutdown",
        rightLabel: "先停住",
        rightShort: "先停",
        rightStrength: "在過載時替自己拉下保護閘",
        rightBlindSpot: "你可能在真正需要幫忙前就先失去連結",
        rightGrowth: "把停住變成短暫調節，並保留和外界重新連上的路",
      },
      {
        key: "pressure_direction",
        leftKey: "internalize_stress",
        leftLabel: "往內吞壓",
        leftShort: "往內吞",
        leftStrength: "把外界干擾收住，不讓場面更亂",
        leftBlindSpot: "別人不一定知道你已經撐到哪裡",
        leftGrowth: "在壓力還沒爆表前，先讓可信任的人知道你的狀態",
        rightKey: "externalize_stress",
        rightLabel: "往外釋壓",
        rightShort: "往外釋壓",
        rightStrength: "讓壓力有出口，不至於在體內悶燒",
        rightBlindSpot: "你有時會讓周圍先承接到你的風暴",
        rightGrowth: "先分辨你要的是支援，還是只是暫時宣洩",
      },
    ],
    tagLabels: {
      alert: "警報感",
      containment: "收束力",
      urgency: "急迫感",
      recovery: "恢復力",
      frustration: "挫折張力",
      support_need: "支援需求",
    },
    profileTitles: {
      quadrant_ll: "壓力佈防者",
      quadrant_lr: "硬撐放電者",
      quadrant_rl: "靜止承壓者",
      quadrant_rr: "風暴宣洩者",
      balanced_integration: "韌性調節者",
      balanced_bridge: "壓力換檔者",
      tension_mirror: "警報拉扯者",
      tension_pivot: "保命切換者",
    },
    promptTemplates: [
      "當{context}時，你的身心第一波最像哪一種反應？",
      "遇到{context}這種高壓時刻，你通常怎麼跟自己合作？",
      "如果{context}，你最常先做哪一步？",
      "在{context}的當下，你最強烈的內在需求通常是什麼？",
    ],
    contexts: [
      "截止時間突然提前",
      "連續好幾件小事一起卡住",
      "被臨時點名要求立刻回應",
      "手上的任務越堆越多卻沒空整理",
      "身體狀態不好，卻還得硬著頭皮撐住",
      "原本的計畫整個失控",
      "有人一直催你、提醒你、盯著你",
      "你必須在很短時間內給出答案",
    ],
    packs: [
      makePack([
        { text: "我會立刻開始收拾局面，至少先抓一件能動的事。", tags: { urgency: 1, containment: 1 } },
        { text: "我會先把自己撐住，再一邊動一邊找出口。", tags: { urgency: 1, support_need: 1 } },
        { text: "我會先停一下，因為系統太滿時我沒辦法硬推。", tags: { alert: 1, containment: 1 } },
        { text: "我很容易瞬間炸開，需要先把壓力放出去。", tags: { frustration: 1, support_need: 1 } },
      ]),
      makePack([
        { text: "我靠做事讓自己不要被壓力吞掉。", tags: { urgency: 1, recovery: 1 } },
        { text: "我一邊做、一邊想找個地方把壓力排掉。", tags: { support_need: 1, recovery: 1 } },
        { text: "我會先暫停，讓身體不要再往警報裡衝。", tags: { alert: 1, containment: 1 } },
        { text: "我需要把那股壓力宣洩出去，不然真的撐不住。", tags: { frustration: 1, support_need: 1 } },
      ]),
      makePack([
        { text: "先拆出優先順序，讓事情至少不要全面失控。", tags: { containment: 1, urgency: 1 } },
        { text: "先把場面撐過去，再找人或出口幫我回到正常。", tags: { urgency: 1, support_need: 1 } },
        { text: "先讓自己脫離刺激，等腦袋能重新接線。", tags: { alert: 1, recovery: 1 } },
        { text: "先讓情緒出去，不然我連下一步都想不到。", tags: { frustration: 1, support_need: 1 } },
      ]),
      makePack([
        { text: "我需要重新掌握一點點控制感。", tags: { containment: 1, urgency: 1 } },
        { text: "我需要有人或什麼東西幫我分掉這股壓力。", tags: { support_need: 1, recovery: 1 } },
        { text: "我需要先停機一下，讓警報不要再往上衝。", tags: { alert: 1, containment: 1 } },
        { text: "我需要馬上有出口，否則壓力會在我身上爆掉。", tags: { frustration: 1, support_need: 1 } },
      ]),
    ],
  },
  {
    slug: "decision-making-style",
    code: "DM",
    icon: "◇",
    title: "你做決定時，習慣靠哪套系統？",
    shortTitle: "決策風格",
    subtitle: "你的決策風格，透露你做選擇時最在乎的東西。",
    description: "從衡量方式、直覺速度與他人參與度，看見你的決策慣性。",
    cardDescription: "看你做決定時是先比較、先感覺、先自己定，還是先聽回音。",
    heroCopy: "有些人需要先拆清楚，有些人要先等感覺到位；有些人自己做主，有些人會先聽回音。這就是你的決策語言。",
    shareTitle: "決策風格心理測驗",
    shareDescription: "測出你做選擇時最常依靠的思考系統。",
    themeColor: "#8d7451",
    themeColorSoft: "#e3d0b2",
    themeInk: "#221a13",
    themeGlow: "rgba(141,116,81,0.28)",
    domain: "做選擇與承擔結果",
    surpriseLine: "你做決定的速度與節奏，反映你想確認的東西不一樣。",
    axes: [
      {
        key: "decision_process",
        leftKey: "deliberate",
        leftLabel: "審慎衡量",
        leftShort: "衡量",
        leftStrength: "把條件與風險看得比較完整",
        leftBlindSpot: "你可能會在資訊還沒完美前遲遲不肯動",
        leftGrowth: "替決定設一個足夠清楚、能開始行動的門檻",
        rightKey: "instinctive",
        rightLabel: "直感決定",
        rightShort: "直感",
        rightStrength: "快速抓到真正有共鳴的方向",
        rightBlindSpot: "有時你會在感覺很亮的時候低估後續成本",
        rightGrowth: "讓直覺保留，但替它補一張現實清單",
      },
      {
        key: "decision_reference",
        leftKey: "independent",
        leftLabel: "自己定奪",
        leftShort: "自己定",
        leftStrength: "不容易被外界意見輕易帶走",
        leftBlindSpot: "你可能會把求助誤會成搖擺",
        leftGrowth: "在不失去主導的前提下，借別人的眼睛幫自己校準",
        rightKey: "collaborative",
        rightLabel: "聽回音後定",
        rightShort: "聽回音",
        rightStrength: "能把別人的觀點納入，減少盲點",
        rightBlindSpot: "你可能會在很多聲音裡失去自己的原始傾向",
        rightGrowth: "先記下你第一個答案，再去聽別人的想法",
      },
    ],
    tagLabels: {
      clarity: "清晰需求",
      intuition: "感覺導向",
      autonomy: "自主感",
      resonance: "回音需求",
      caution: "風險意識",
      momentum: "行動推力",
    },
    profileTitles: {
      quadrant_ll: "冷靜定盤者",
      quadrant_lr: "共感衡量者",
      quadrant_rl: "直覺主導者",
      quadrant_rr: "回音決策者",
      balanced_integration: "雙軌判斷者",
      balanced_bridge: "彈性取捨者",
      tension_mirror: "選擇拉扯者",
      tension_pivot: "門檻轉換者",
    },
    promptTemplates: [
      "當{context}時，你做決定的第一個習慣通常是什麼？",
      "遇到{context}這種選擇題，你會怎麼跟自己的想法相處？",
      "如果{context}，你最可能先採取哪一步？",
      "在{context}的那一刻，真正左右你的通常是什麼？",
    ],
    contexts: [
      "兩個都不錯的機會同時出現",
      "要買一個不算便宜但又很想要的東西",
      "朋友突然提出一個臨時邀約",
      "需要在短時間內選一個方向",
      "這個選擇會影響別人的感受",
      "你在考慮要不要離開熟悉環境",
      "有人找你談合作，但資訊還不完整",
      "你原本的計畫需要因為新條件而改動",
    ],
    packs: [
      makePack([
        { text: "我會先列比較點，弄清楚自己到底在選什麼。", tags: { clarity: 1, caution: 1 } },
        { text: "我會先想清楚條件，再聽幾個值得信任的人怎麼看。", tags: { clarity: 1, resonance: 1 } },
        { text: "我通常很快知道自己比較想選哪個，理由是之後補上的。", tags: { intuition: 1, autonomy: 1 } },
        { text: "我需要先聽到幾種回音，感覺才會真正成形。", tags: { intuition: 1, resonance: 1 } },
      ]),
      makePack([
        { text: "先把標準釐清，我才不會在情緒裡繞圈。", tags: { clarity: 1, caution: 1 } },
        { text: "我會先有一個理性草稿，再看誰能幫我補盲點。", tags: { clarity: 1, resonance: 1 } },
        { text: "我會先抓住那個最有共鳴的方向，否則會越想越散。", tags: { intuition: 1, momentum: 1 } },
        { text: "我想聽聽別人怎麼感受，因為答案對我來說也包含人和現場的回音。", tags: { resonance: 1, intuition: 1 } },
      ]),
      makePack([
        { text: "先把條件縮成幾個核心變數再決定。", tags: { clarity: 1, caution: 1 } },
        { text: "先確認我自己的傾向，再找可信的人校準。", tags: { autonomy: 1, resonance: 1 } },
        { text: "先順著最有感的那個方向做個小測試。", tags: { intuition: 1, momentum: 1 } },
        { text: "先去聽現場反應，因為答案常常藏在互動裡。", tags: { resonance: 1, intuition: 1 } },
      ]),
      makePack([
        { text: "我需要知道這個決定為什麼合理。", tags: { clarity: 1, caution: 1 } },
        { text: "我需要確定自己沒漏掉重要的人和重要的面向。", tags: { clarity: 1, resonance: 1 } },
        { text: "我需要一種『就是它了』的內在確定感。", tags: { intuition: 1, autonomy: 1 } },
        { text: "我需要聽見一些真實回音，讓決定不只是我一個人的腦補。", tags: { resonance: 1, intuition: 1 } },
      ]),
    ],
  },
  {
    slug: "relationship-style",
    code: "RS",
    icon: "♡",
    title: "在關係裡，你最常用哪種靠近方式？",
    shortTitle: "關係風格",
    subtitle: "你怎麼靠近、怎麼退開，常常比你說了什麼更真實。",
    description: "從受傷、靠近、表達需求與修復方式，看見你的關係節奏。",
    cardDescription: "測出你在愛與關係裡更像安心靠近、溫柔配合、理智防守，還是又愛又怕。",
    heroCopy: "有的人在關係裡很直接，有的人要先觀察安全度；有的人能說需要，有的人會先配合。這就是你的靠近方式。",
    shareTitle: "關係風格心理測驗",
    shareDescription: "看見你在親密與靠近裡最常啟動的節奏。",
    themeColor: "#b06a70",
    themeColorSoft: "#efc3c8",
    themeInk: "#251618",
    themeGlow: "rgba(176,106,112,0.27)",
    domain: "靠近、受傷與修復關係",
    surpriseLine: "你在關係裡最先保護的東西，很值得被溫柔理解。",
    axes: [
      {
        key: "attachment_safety",
        leftKey: "secure",
        leftLabel: "安心靠近",
        leftShort: "安心靠近",
        leftStrength: "在靠近時保有穩定感，不必一直猜",
        leftBlindSpot: "你有時會低估別人其實比你更需要被安撫",
        leftGrowth: "保留穩定感的同時，也多聽一點對方沒說出口的害怕",
        rightKey: "guarded",
        rightLabel: "先設防再靠近",
        rightShort: "先設防",
        rightStrength: "不會把自己的脆弱輕易交出去",
        rightBlindSpot: "別人可能來得及喜歡你，卻來不及真正靠近你",
        rightGrowth: "讓保護留著，但別把所有靠近都當成風險",
      },
      {
        key: "relationship_expression",
        leftKey: "direct",
        leftLabel: "直接表達",
        leftShort: "直接",
        leftStrength: "能把需求和不舒服講得比較清楚",
        leftBlindSpot: "你有時會把誠實講得太快，讓對方來不及消化",
        leftGrowth: "在真話前面加一點溫度，效果通常會更好",
        rightKey: "accommodating",
        rightLabel: "先配合後消化",
        rightShort: "先配合",
        rightStrength: "能先顧到關係氛圍，不急著把場面推到對立",
        rightBlindSpot: "你可能把委屈藏得太久，最後只剩疲累",
        rightGrowth: "把配合變成選擇，也把自己的需要一起放進來",
      },
    ],
    tagLabels: {
      tenderness: "親密需求",
      caution: "安全感",
      clarity: "說清楚需求",
      harmony: "關係氛圍",
      longing: "被在乎感",
      self_protection: "自我保護",
    },
    profileTitles: {
      quadrant_ll: "坦白安定者",
      quadrant_lr: "溫柔穩住者",
      quadrant_rl: "邊界觀察者",
      quadrant_rr: "敏感配合者",
      balanced_integration: "成熟靠近者",
      balanced_bridge: "柔韌相處者",
      tension_mirror: "又愛又怕者",
      tension_pivot: "關係換氣者",
    },
    promptTemplates: [
      "當{context}時，你在關係裡的第一反應通常比較像哪一種？",
      "遇到{context}這種時刻，你多半怎麼安放自己和對方？",
      "如果{context}，你最容易先做哪一步？",
      "在{context}的那一刻，你最在意被保護的是什麼？",
    ],
    contexts: [
      "喜歡的人突然變得有點冷淡",
      "朋友回覆速度明顯變慢",
      "你需要說出一件讓你不舒服的事",
      "對方沒做到原本答應你的事",
      "一段關係開始有想更近一步的可能",
      "吵完架之後還要不要主動靠近",
      "你有需求，但怕一說出口就破壞氣氛",
      "對方的情緒起伏很大，讓你也跟著緊繃",
    ],
    packs: [
      makePack([
        { text: "我會想直接確認狀況，不想靠猜維持關係。", tags: { clarity: 1, tenderness: 1 } },
        { text: "我會先穩住關係氛圍，再挑一個不刺人的方式說清楚。", tags: { harmony: 1, clarity: 1 } },
        { text: "我會先退一步觀察，不想太快把自己丟出去。", tags: { caution: 1, self_protection: 1 } },
        { text: "我會先配合表面，回頭自己消化那些不安。", tags: { harmony: 1, self_protection: 1 } },
      ]),
      makePack([
        { text: "我會想把話講明白，因為關係對我來說值得面對。", tags: { clarity: 1, tenderness: 1 } },
        { text: "我會先顧好彼此的氣氛，再慢慢把真實說出來。", tags: { harmony: 1, tenderness: 1 } },
        { text: "我需要先確認安全，不然我很難真的打開。", tags: { caution: 1, self_protection: 1 } },
        { text: "我會先讓事情過去，但其實心裡沒有真的過去。", tags: { harmony: 1, longing: 1 } },
      ]),
      makePack([
        { text: "先問清楚、先說清楚，讓誤會不要發酵。", tags: { clarity: 1, tenderness: 1 } },
        { text: "先找一個對方比較能接住的方式開口。", tags: { harmony: 1, clarity: 1 } },
        { text: "先觀察對方現在值不值得我打開那麼多。", tags: { caution: 1, self_protection: 1 } },
        { text: "先把自己縮小一點，看看關係能不能先穩住。", tags: { harmony: 1, longing: 1 } },
      ]),
      makePack([
        { text: "我在意的是彼此還有沒有真實的連結。", tags: { tenderness: 1, clarity: 1 } },
        { text: "我在意的是就算有衝突，也不要把關係弄碎。", tags: { harmony: 1, tenderness: 1 } },
        { text: "我在意的是不要讓自己的脆弱變成別人的把柄。", tags: { caution: 1, self_protection: 1 } },
        { text: "我在意的是別因為說太多，失去那段關係。", tags: { longing: 1, harmony: 1 } },
      ]),
    ],
  },
  {
    slug: "hidden-fears",
    code: "HF",
    icon: "◌",
    title: "你的隱性恐懼最常躲在哪裡？",
    shortTitle: "隱性恐懼",
    subtitle: "你不一定覺得自己害怕，但生活的保護動作其實很誠實。",
    description: "從退縮、控制、曝光與失敗感裡，看見你真正怕失去的是什麼。",
    cardDescription: "照出你最常在意的是被拒絕、失敗、失控，還是乾脆先消失。",
    heroCopy: "很多恐懼會藏在你的過度準備、過度退讓、過度控制或突然消失裡。這份測驗會把那個影子照出來。",
    shareTitle: "隱性恐懼心理測驗",
    shareDescription: "看見你最常用什麼方式保護那些沒被說出口的害怕。",
    themeColor: "#7d5f72",
    themeColorSoft: "#d8c2d1",
    themeInk: "#1f1820",
    themeGlow: "rgba(125,95,114,0.27)",
    domain: "害怕暴露、失敗與失控",
    surpriseLine: "很多時候你以為自己只是謹慎，其實那也是害怕在說話。",
    axes: [
      {
        key: "fear_source",
        leftKey: "rejection_sensitive",
        leftLabel: "害怕被拒絕",
        leftShort: "怕被拒絕",
        leftStrength: "對人際溫度與細微變化特別敏感",
        leftBlindSpot: "你可能太早把模糊訊號解讀成否定",
        leftGrowth: "讓不確定停留久一點，別急著替別人的沉默下判決",
        rightKey: "failure_sensitive",
        rightLabel: "害怕失敗",
        rightShort: "怕失敗",
        rightStrength: "對成果、風險與後果有高度警覺",
        rightBlindSpot: "你有時會因為怕輸而不敢真正投入",
        rightGrowth: "把失敗看成資訊，不要把它直接升級成自我評價",
      },
      {
        key: "fear_defense",
        leftKey: "control_seeking",
        leftLabel: "用掌控保護自己",
        leftShort: "掌控保護",
        leftStrength: "靠安排與預備降低不確定感",
        leftBlindSpot: "當你太想掌控時，心會比事情還累",
        leftGrowth: "把掌控感用在可行動的部分，其他未知先留給時間",
        rightKey: "withdrawal",
        rightLabel: "用退開保護自己",
        rightShort: "退開保護",
        rightStrength: "知道自己過載時需要拉開距離",
        rightBlindSpot: "你可能在關係或機會真正靠近前就先抽離",
        rightGrowth: "退開可以，但替自己留一條回來的路",
      },
    ],
    tagLabels: {
      vigilance: "警戒感",
      validation: "被肯定需求",
      control_need: "掌控需求",
      retreat: "退開慣性",
      shame: "羞愧感",
      courage: "靠近勇氣",
    },
    profileTitles: {
      quadrant_ll: "敏感佈防者",
      quadrant_lr: "怕傷退守者",
      quadrant_rl: "完美緊控者",
      quadrant_rr: "低調避險者",
      balanced_integration: "深層自覺者",
      balanced_bridge: "謹慎探索者",
      tension_mirror: "害怕交叉者",
      tension_pivot: "防衛調整者",
    },
    promptTemplates: [
      "當{context}時，你內在第一個被觸發的害怕通常更像哪一種？",
      "遇到{context}這種場景，你多半怎麼保護自己？",
      "如果{context}，你最容易先做哪件事？",
      "在{context}的那一刻，你最不想失去的是什麼？",
    ],
    contexts: [
      "你得把作品或想法拿出去給人看",
      "進入一個誰都不熟的新環境",
      "自己做錯了一件其實不算大的事",
      "有人突然問你最近過得怎樣",
      "一個原本期待的計畫可能會失敗",
      "關係裡的訊號開始變得不確定",
      "你需要主動開口求助",
      "事情發展明顯超出原本預期",
    ],
    packs: [
      makePack([
        { text: "我會先感受別人會不會不要我、看不起我。", tags: { validation: 1, vigilance: 1 } },
        { text: "我會先努力穩住局面，不想讓別人看見我慌。", tags: { control_need: 1, shame: 1 } },
        { text: "我會先退一下，避免自己太快暴露在風險裡。", tags: { retreat: 1, vigilance: 1 } },
        { text: "我最先想到的是如果搞砸了，後面會多難收。", tags: { shame: 1, control_need: 1 } },
      ]),
      makePack([
        { text: "我會先看對方的表情和溫度，判斷自己安不安全。", tags: { validation: 1, vigilance: 1 } },
        { text: "我會開始想怎麼把變數收回自己手上。", tags: { control_need: 1, courage: 1 } },
        { text: "我通常先抽離一點，不讓自己一下子陷太深。", tags: { retreat: 1, vigilance: 1 } },
        { text: "我會先想如何降低出錯風險，再慢慢靠近想做成的方向。", tags: { shame: 1, control_need: 1 } },
      ]),
      makePack([
        { text: "先確認別人的態度，決定我能不能再往前。", tags: { validation: 1, vigilance: 1 } },
        { text: "先把細節安排好，至少不要讓局面太失控。", tags: { control_need: 1, courage: 1 } },
        { text: "先讓自己退開一點，等安全感回來再說。", tags: { retreat: 1, vigilance: 1 } },
        { text: "先降低風險，不要讓自己面對太大的失敗感。", tags: { shame: 1, control_need: 1 } },
      ]),
      makePack([
        { text: "我最怕的是被冷掉、被否定、被覺得不值得。", tags: { validation: 1, shame: 1 } },
        { text: "我最怕的是事情完全不在我能處理的範圍內。", tags: { control_need: 1, vigilance: 1 } },
        { text: "我最怕的是一靠近就受傷，還來不及保護自己。", tags: { retreat: 1, validation: 1 } },
        { text: "我最怕的是失敗之後要面對那種很重的自責。", tags: { shame: 1, control_need: 1 } },
      ]),
    ],
  },
  {
    slug: "motivation-style",
    code: "MS",
    icon: "✦",
    title: "你最容易被哪一種動機點燃？",
    shortTitle: "動機風格",
    subtitle: "你的動力有自己的火種，不同時候會需要不同燃料。",
    description: "從起步方式、長期推進與回饋需求，看見你真正的驅動源。",
    cardDescription: "看你是被成就感、意義感、穩定節奏，還是衝刺火花推著走。",
    heroCopy: "有些人要看見成果才有力，有些人要先感到值得；有人靠穩定，有人靠爆發。這份測驗會照出你真正的點火方式。",
    shareTitle: "動機風格心理測驗",
    shareDescription: "看見你最容易被什麼樣的內在燃料推著走。",
    themeColor: "#92804a",
    themeColorSoft: "#e4dbb3",
    themeInk: "#211d13",
    themeGlow: "rgba(146,128,74,0.29)",
    domain: "起步、推進與維持動力",
    surpriseLine: "你的動力需要適合你的燃料與節奏。",
    axes: [
      {
        key: "motivation_source",
        leftKey: "achievement_driven",
        leftLabel: "成就驅動",
        leftShort: "成就",
        leftStrength: "被目標、成果與可見進步推著走",
        leftBlindSpot: "當外在回報變少時，你可能很快失去心情",
        leftGrowth: "讓成果感和價值感同時存在，你會走得更久",
        rightKey: "meaning_driven",
        rightLabel: "意義驅動",
        rightShort: "意義",
        rightStrength: "只要覺得值得，就能投入得很深",
        rightBlindSpot: "如果感覺不對味，你可能很難強迫自己前進",
        rightGrowth: "替價值感找一個具體結構，不要全靠感受維持",
      },
      {
        key: "motivation_rhythm",
        leftKey: "steady",
        leftLabel: "穩定推進",
        leftShort: "穩推",
        leftStrength: "靠節奏把長期事情慢慢做出來",
        leftBlindSpot: "有時你會為了穩而少了一點熱度與冒險",
        leftGrowth: "在穩定之外，允許一點偶爾的火花幫你加速",
        rightKey: "pulse_driven",
        rightLabel: "脈衝爆發",
        rightShort: "爆發",
        rightStrength: "一旦被點燃，能在短時間內衝出很強的動能",
        rightBlindSpot: "你有時會把後續維持丟給未來的自己",
        rightGrowth: "把爆發力接回日常節奏，別讓靈感只剩高峰",
      },
    ],
    tagLabels: {
      reward: "回饋需求",
      meaning: "意義感",
      pace: "節奏感",
      spark: "點火感",
      endurance: "持續力",
      comparison: "比較敏感",
    },
    profileTitles: {
      quadrant_ll: "穩定攻頂者",
      quadrant_lr: "衝刺成就者",
      quadrant_rl: "深意耕耘者",
      quadrant_rr: "靈感燃燒者",
      balanced_integration: "動機整流者",
      balanced_bridge: "節奏策動者",
      tension_mirror: "動力斷續者",
      tension_pivot: "火力調整者",
    },
    promptTemplates: [
      "當{context}時，最能把你推起來的動力通常是哪一種？",
      "遇到{context}這種狀態，你多半怎麼和自己的動力相處？",
      "如果{context}，你最可能先做哪一步？",
      "在{context}的那一刻，真正讓你想繼續的通常是什麼？",
    ],
    contexts: [
      "清單很多但能量有限",
      "你突然遇到一個超有感的題目",
      "工作只剩例行與瑣碎",
      "沒有人催你、也沒有人盯進度",
      "眼前有一個需要長期投入的目標",
      "你看見別人的進度比你快",
      "你忽然得到一段空檔能做自己的事",
      "努力一陣子後，成果暫時還看不到",
    ],
    packs: [
      makePack([
        { text: "我需要看見明確進度，這樣比較有推進感。", tags: { reward: 1, pace: 1 } },
        { text: "我需要知道自己為什麼做，這樣穩穩做下去才有感。", tags: { meaning: 1, endurance: 1 } },
        { text: "我會等那股火真的上來，再一次衝很多。", tags: { spark: 1, reward: 1 } },
        { text: "只要我真心覺得有意思，我會瞬間全開。", tags: { spark: 1, meaning: 1 } },
      ]),
      makePack([
        { text: "我會先把它切成可完成的小段，讓自己有連續感。", tags: { pace: 1, reward: 1 } },
        { text: "我會先把它跟自己在乎的東西連起來，不然做不久。", tags: { meaning: 1, endurance: 1 } },
        { text: "我比較像等到狀態到位時，一口氣往前推。", tags: { spark: 1, reward: 1 } },
        { text: "我需要感覺心裡亮起來，不然很難假裝有動力。", tags: { spark: 1, meaning: 1 } },
      ]),
      makePack([
        { text: "先安排一個我明天也做得到的小節奏。", tags: { pace: 1, endurance: 1 } },
        { text: "先提醒自己這件事跟我真正想成為的人有什麼關係。", tags: { meaning: 1, endurance: 1 } },
        { text: "先找一個能讓我立刻進入狀態的切口。", tags: { spark: 1, reward: 1 } },
        { text: "先碰最讓我有感的部分，讓自己重新被點燃。", tags: { spark: 1, meaning: 1 } },
      ]),
      makePack([
        { text: "我想要看見努力真的有產出。", tags: { reward: 1, comparison: 1 } },
        { text: "我想確定自己正在做一件有內容、有意義的事。", tags: { meaning: 1, endurance: 1 } },
        { text: "我想要有那種『現在就來吧』的衝勁。", tags: { spark: 1, reward: 1 } },
        { text: "我想被某種真正在乎的感覺重新點亮。", tags: { spark: 1, meaning: 1 } },
      ]),
    ],
  },
  {
    slug: "social-behavior",
    code: "SB",
    icon: "☰",
    title: "你的社交行為更偏向哪一種節奏？",
    shortTitle: "社交行為",
    subtitle: "你的進場、互動與耗電方式，組成獨特的社交節奏。",
    description: "從進場方式、存在感與能量消耗，看見你的社交模式。",
    cardDescription: "測出你在社交裡是觀察派、表現派、選擇性靠近，還是擴張型互動者。",
    heroCopy: "有人進場先觀察，有人一出場就有存在感；有人只想深聊，有人能跟很多人流動互動。社交是一種能量使用方式。",
    shareTitle: "社交行為心理測驗",
    shareDescription: "看見你在社交場景裡的靠近方式與耗電節奏。",
    themeColor: "#53767d",
    themeColorSoft: "#c0d9dc",
    themeInk: "#152123",
    themeGlow: "rgba(83,118,125,0.28)",
    domain: "進入社交、維持存在與回收能量",
    surpriseLine: "你在場的方式有自己的節奏與溫度。",
    axes: [
      {
        key: "social_presence",
        leftKey: "observant",
        leftLabel: "觀察進場",
        leftShort: "觀察",
        leftStrength: "先讀懂場域，再決定自己怎麼放進去",
        leftBlindSpot: "別人可能以為你沒感覺，其實你只是還沒進場",
        leftGrowth: "當你已經讀懂夠多時，給自己一個小小的起手式",
        rightKey: "performative",
        rightLabel: "存在感進場",
        rightShort: "存在感",
        rightStrength: "能快速建立互動與場面溫度",
        rightBlindSpot: "你有時會讓自己一直保持亮著，忘了其實已經累了",
        rightGrowth: "讓表達有節奏，讓高輸出也能有回氣空間",
      },
      {
        key: "social_range",
        leftKey: "selective",
        leftLabel: "選擇性靠近",
        leftShort: "選擇性",
        leftStrength: "把能量留給真正想連結的人",
        leftBlindSpot: "你可能錯過一些其實值得打開的連結",
        leftGrowth: "不必對所有人都開，但可以讓一點陌生感慢慢變熟",
        rightKey: "expansive",
        rightLabel: "擴張型互動",
        rightShort: "擴張型",
        rightStrength: "能在不同人之間快速流動和建立橋樑",
        rightBlindSpot: "你有時會在很多連結裡分散掉自己的核心能量",
        rightGrowth: "在廣度之外，替自己留下幾段真正深的關係",
      },
    ],
    tagLabels: {
      warmth: "互動溫度",
      privacy: "保留感",
      stamina: "社交續航",
      spotlight: "被看見感",
      depth: "深聊需求",
      agility: "場域流動",
    },
    profileTitles: {
      quadrant_ll: "靜水觀察者",
      quadrant_lr: "場域編織者",
      quadrant_rl: "亮場精準者",
      quadrant_rr: "流動連結者",
      balanced_integration: "社交整頻者",
      balanced_bridge: "溫度切換者",
      tension_mirror: "耗電拉扯者",
      tension_pivot: "人群換檔者",
    },
    promptTemplates: [
      "當{context}時，你在社交裡的第一個動作通常比較像哪一種？",
      "遇到{context}這種場合，你多半怎麼安放自己的能量？",
      "如果{context}，你最容易先做哪一步？",
      "在{context}的那一刻，你最在意的是什麼？",
    ],
    contexts: [
      "剛走進一個陌生聚會",
      "聊天桌突然安靜下來",
      "你想認識新朋友卻還在暖機",
      "一整天都在社交，快沒電了",
      "小組討論開始需要有人帶動",
      "你發現現場有人特別注意你",
      "你想離場但活動還沒結束",
      "熟人和陌生人混在同一個場合裡",
    ],
    packs: [
      makePack([
        { text: "我會先看一輪氣氛，等抓到節奏再靠近。", tags: { privacy: 1, agility: 1 } },
        { text: "我會先跟少數有感的人接上，不急著全面打開。", tags: { depth: 1, warmth: 1 } },
        { text: "我通常很自然就會讓人注意到我，互動也比較快開始。", tags: { spotlight: 1, agility: 1 } },
        { text: "我會在不同人之間流動，讓場子慢慢熱起來。", tags: { warmth: 1, stamina: 1 } },
      ]),
      makePack([
        { text: "我需要先保留一點空間，這樣比較不會亂耗。", tags: { privacy: 1, stamina: 1 } },
        { text: "我會把力氣放在少數我真的想聊的人身上。", tags: { depth: 1, privacy: 1 } },
        { text: "我會繼續把場面撐住，不想讓氣氛掉下去。", tags: { spotlight: 1, warmth: 1 } },
        { text: "我會靠流動互動讓自己保持在舒服的節奏裡。", tags: { agility: 1, stamina: 1 } },
      ]),
      makePack([
        { text: "先找一個觀察點，讓自己慢慢進場。", tags: { privacy: 1, agility: 1 } },
        { text: "先靠近一個我覺得有機會聊深的人。", tags: { depth: 1, warmth: 1 } },
        { text: "先把話題接起來，讓大家有東西可以跟。", tags: { spotlight: 1, warmth: 1 } },
        { text: "先繞場、先串連，讓互動自己長出來。", tags: { agility: 1, stamina: 1 } },
      ]),
      makePack([
        { text: "我在意自己能不能自然、不被過度看見。", tags: { privacy: 1, stamina: 1 } },
        { text: "我在意有沒有一段是真的、有內容的連結。", tags: { depth: 1, warmth: 1 } },
        { text: "我在意場子不要冷掉，也不想自己像沒來過。", tags: { spotlight: 1, warmth: 1 } },
        { text: "我在意的是能量要流得動，不要卡在尷尬裡。", tags: { agility: 1, stamina: 1 } },
      ]),
    ],
  },
  {
    slug: "thinking-patterns",
    code: "TP",
    icon: "⌘",
    title: "你的思考模式更偏向哪一邊？",
    shortTitle: "思考模式",
    subtitle: "你是怎麼理解訊息、看見重點、抓住方向的？",
    description: "從你讀訊號、處理資訊與預判走向的方式，看見你的思考路徑。",
    cardDescription: "看你是偏邏輯還是直覺、偏細節還是大局。",
    heroCopy: "有些人的腦先抓結構，有些人的腦先抓氣味；有人看細節就能安心，有人先看到整體畫面。這就是你的思考語言。",
    shareTitle: "思考模式心理測驗",
    shareDescription: "測出你理解訊息與看見重點的思考偏好。",
    themeColor: "#4f6d8d",
    themeColorSoft: "#bfd2e8",
    themeInk: "#151d28",
    themeGlow: "rgba(79,109,141,0.28)",
    domain: "理解訊息與看見重點",
    surpriseLine: "你的腦習慣先看見某一種線索，這讓你的思考很有辨識度。",
    axes: [
      {
        key: "thinking_input",
        leftKey: "logical",
        leftLabel: "邏輯辨識",
        leftShort: "邏輯",
        leftStrength: "先找因果、漏洞與可驗證的脈絡",
        leftBlindSpot: "你可能會把模糊但重要的感受訊號放得太後面",
        leftGrowth: "在判斷之前，也替那些說不清的線索留一點位置",
        rightKey: "intuitive_thinking",
        rightLabel: "直覺辨識",
        rightShort: "直覺",
        rightStrength: "先抓到整體氛圍與隱含方向",
        rightBlindSpot: "你有時會很早就覺得自己知道，卻少了驗證",
        rightGrowth: "讓直覺先開門，再請邏輯幫你確認房間裡有什麼",
      },
      {
        key: "thinking_scope",
        leftKey: "detail_first",
        leftLabel: "細節先行",
        leftShort: "細節",
        leftStrength: "能從具體訊號看出真正的差別",
        leftBlindSpot: "你可能在細節裡停太久，錯過大方向的流動",
        leftGrowth: "偶爾抬頭看整體，能讓你的細節更有意義",
        rightKey: "big_picture",
        rightLabel: "大局先行",
        rightShort: "大局",
        rightStrength: "先抓到主軸與整體趨勢",
        rightBlindSpot: "你有時會把重要細節當成之後再說，最後反而卡住",
        rightGrowth: "讓大方向落地時，多補兩個最關鍵的細節錨點",
      },
    ],
    tagLabels: {
      clarity: "條理感",
      nuance: "細微感",
      foresight: "走向感",
      verification: "驗證需求",
      synthesis: "整合力",
      patterning: "模式感",
    },
    profileTitles: {
      quadrant_ll: "精準拆解者",
      quadrant_lr: "結構預判者",
      quadrant_rl: "敏銳捕捉者",
      quadrant_rr: "全景感知者",
      balanced_integration: "雙腦整合者",
      balanced_bridge: "層次思考者",
      tension_mirror: "訊號拉扯者",
      tension_pivot: "視角切換者",
    },
    promptTemplates: [
      "當{context}時，你的大腦最先抓住的通常是什麼？",
      "遇到{context}這種資訊場景，你多半怎麼讓自己理解？",
      "如果{context}，你最可能先採取哪一步？",
      "在{context}的那一刻，你最信任的是哪一種線索？",
    ],
    contexts: [
      "你看到一個新提案或新企劃",
      "你聽到一則半真半假的八卦",
      "你在規劃一趟旅行或一個流程",
      "你要修正一個一直出錯的小系統",
      "你開始思考要不要換跑道",
      "你在看一本資訊量很大的書或長文章",
      "你想理解某個人的反常舉動",
      "你要做一件自己以前沒有做過的事",
    ],
    packs: [
      makePack([
        { text: "我會先找邏輯和線索，看它到底說不說得通。", tags: { clarity: 1, verification: 1 } },
        { text: "我會先抓主軸，再回頭看哪些細節能撐住它。", tags: { synthesis: 1, foresight: 1 } },
        { text: "我會先感覺哪裡不對或哪裡有味道，再慢慢拆。", tags: { patterning: 1, nuance: 1 } },
        { text: "我會先看到整體走向，細節是之後才補上的。", tags: { foresight: 1, synthesis: 1 } },
      ]),
      makePack([
        { text: "我需要有可驗證的結構，不然腦袋會一直卡。", tags: { verification: 1, clarity: 1 } },
        { text: "我會先把訊息放到整體脈絡裡理解。", tags: { synthesis: 1, foresight: 1 } },
        { text: "我會先相信自己對異樣感的捕捉，再看看原因。", tags: { nuance: 1, patterning: 1 } },
        { text: "我會先問這整件事到底在往哪裡走。", tags: { foresight: 1, synthesis: 1 } },
      ]),
      makePack([
        { text: "先拆因果，看看哪一段最需要驗證。", tags: { clarity: 1, verification: 1 } },
        { text: "先抓大方向，再補最重要的兩三個細節。", tags: { synthesis: 1, foresight: 1 } },
        { text: "先記住那些讓我有感的異常點。", tags: { nuance: 1, patterning: 1 } },
        { text: "先畫出整體圖，讓自己知道這件事的輪廓。", tags: { foresight: 1, synthesis: 1 } },
      ]),
      makePack([
        { text: "我最信任能被證明、能被推理的東西。", tags: { verification: 1, clarity: 1 } },
        { text: "我最信任那些能幫我看見主軸與趨勢的線索。", tags: { synthesis: 1, foresight: 1 } },
        { text: "我最信任那個『哪裡怪怪的』的內在提醒。", tags: { nuance: 1, patterning: 1 } },
        { text: "我最信任整體畫面突然對上的那一刻。", tags: { foresight: 1, patterning: 1 } },
      ]),
    ],
  },
  {
    slug: "inner-conflicts",
    code: "IC",
    icon: "◐",
    title: "你心裡最常打架的是哪兩邊？",
    shortTitle: "內在拉扯",
    subtitle: "很多累來自心裡同時住著兩個真實的聲音。",
    description: "從穩定、自由、保護與表達之間的拉扯，看見你最常和自己衝突的地方。",
    cardDescription: "找出你最常在穩定與自由、保護與表達之間怎麼拉扯。",
    heroCopy: "有時兩個方向都是真的。這份測驗想照出你心裡最常互相拔河的那兩股力量。",
    shareTitle: "內在拉扯心理測驗",
    shareDescription: "照出你心裡最常彼此對撞的兩種需求。",
    themeColor: "#7f6856",
    themeColorSoft: "#dfcab9",
    themeInk: "#211a15",
    themeGlow: "rgba(127,104,86,0.28)",
    domain: "穩定、自由、保護與表達之間的拉扯",
    surpriseLine: "你覺得自己矛盾的地方，常常其實是兩種真實需要都很重要。",
    axes: [
      {
        key: "inner_need_axis",
        leftKey: "stability_seeking",
        leftLabel: "想先穩住",
        leftShort: "穩住",
        leftStrength: "在變動裡替自己保住基本安全感",
        leftBlindSpot: "你可能會把想冒險的那一面壓得太久",
        leftGrowth: "讓穩定變成底盤，也讓人生保有繼續長大的空間",
        rightKey: "freedom_seeking",
        rightLabel: "想先活開",
        rightShort: "活開",
        rightStrength: "願意替真實感和生命感留空間",
        rightBlindSpot: "你有時會把想逃離誤會成真正的自由",
        rightGrowth: "在追求自由時，也替自己留一點可持續的結構",
      },
      {
        key: "expression_axis",
        leftKey: "self_protective",
        leftLabel: "先保護自己",
        leftShort: "保護",
        leftStrength: "知道什麼不能隨便交出去",
        leftBlindSpot: "你可能讓很多真正重要的話永遠停在心裡",
        leftGrowth: "保護可以留著，但不要連真實都一起關掉",
        rightKey: "self_expressive",
        rightLabel: "先說出真實",
        rightShort: "表達",
        rightStrength: "願意讓內在被看見，不靠壓抑維持平靜",
        rightBlindSpot: "有時你會在還沒想清楚時就把自己攤開",
        rightGrowth: "讓表達多一點節奏，讓真實更容易被接住",
      },
    ],
    tagLabels: {
      safety: "安全感",
      longing: "想活開",
      truth: "真實需求",
      restraint: "收住自己",
      release: "鬆開壓力",
      courage: "選擇勇氣",
    },
    profileTitles: {
      quadrant_ll: "穩住守心者",
      quadrant_lr: "穩中說真者",
      quadrant_rl: "自由設防者",
      quadrant_rr: "真我冒險者",
      balanced_integration: "雙向整合者",
      balanced_bridge: "拉扯調頻者",
      tension_mirror: "內在拔河者",
      tension_pivot: "轉身生成者",
    },
    promptTemplates: [
      "當{context}時，你心裡最先拉扯起來的通常是哪兩邊？",
      "遇到{context}這種局面，你多半怎麼和自己談判？",
      "如果{context}，你最可能先做哪一步？",
      "在{context}的那一刻，你真正想護住的是什麼？",
    ],
    contexts: [
      "有一個穩定的機會，但你其實沒有那麼心動",
      "你想說真話，卻知道一開口就會改變關係",
      "你很想離開現況，但又怕後果太大",
      "別人的期待和你自己想要的東西不一樣",
      "你很需要休息，但又怕一停下來就落後",
      "你想被理解，卻又怕太赤裸",
      "生活其實很穩，卻開始有一點悶",
      "你突然很想做一件和原本路線完全不同的事",
    ],
    packs: [
      makePack([
        { text: "我會先想怎麼把安全感留住，再說其他。", tags: { safety: 1, restraint: 1 } },
        { text: "我會想穩住局面，但不想再完全吞掉真話。", tags: { safety: 1, truth: 1 } },
        { text: "我會先讓自己保留退路，至少不要被困死。", tags: { longing: 1, restraint: 1 } },
        { text: "我很想直接照內心走，不然會覺得自己越活越小。", tags: { longing: 1, courage: 1 } },
      ]),
      makePack([
        { text: "我通常會先讓自己不要失去基本穩定。", tags: { safety: 1, restraint: 1 } },
        { text: "我會試著找一種不把自己關掉的穩定方式。", tags: { truth: 1, safety: 1 } },
        { text: "我會一邊想逃開，一邊又把自己收回去保護。", tags: { longing: 1, restraint: 1 } },
        { text: "我更怕長期活得不像自己，所以會想把真話放出來。", tags: { truth: 1, courage: 1 } },
      ]),
      makePack([
        { text: "先保住底盤，至少不要讓事情一下子失控。", tags: { safety: 1, restraint: 1 } },
        { text: "先替真實留一個出口，不想再只做看起來安全的選擇。", tags: { truth: 1, safety: 1 } },
        { text: "先留後手，這樣我才有空間去想到底要不要改變。", tags: { longing: 1, restraint: 1 } },
        { text: "先做一個比較像自己的動作，哪怕很小也好。", tags: { truth: 1, courage: 1 } },
      ]),
      makePack([
        { text: "我最怕的是一切失去支點。", tags: { safety: 1, restraint: 1 } },
        { text: "我最怕的是為了平靜把自己悶到不見。", tags: { truth: 1, safety: 1 } },
        { text: "我最怕的是一靠近自由就失去保護。", tags: { longing: 1, restraint: 1 } },
        { text: "我最怕的是再不說真話，我會越來越不像自己。", tags: { truth: 1, courage: 1 } },
      ]),
    ],
  },
  {
    slug: "self-discipline-vs-impulse",
    code: "SD",
    icon: "▣",
    title: "你在自律與衝動之間偏向哪一邊？",
    shortTitle: "自律與衝動",
    subtitle: "你面對誘惑與疲累時，有一套和自己談判的方式。",
    description: "從誘惑、拖延、補償與長期目標，看見你的自我管理慣性。",
    cardDescription: "看你怎麼面對小誘惑、疲憊感、長期目標與即時舒服。",
    heroCopy: "每個人都會被舒服感吸引，也都知道未來很重要。關鍵在於你用什麼方式跟當下的自己談判。",
    shareTitle: "自律與衝動心理測驗",
    shareDescription: "看見你在當下舒服與長期目標之間最常怎麼選。",
    themeColor: "#6f6b4e",
    themeColorSoft: "#d8d2af",
    themeInk: "#1c1b14",
    themeGlow: "rgba(111,107,78,0.29)",
    domain: "當下舒服、長期目標與自我管理",
    surpriseLine: "你的意志需要適合你的支撐方式。",
    axes: [
      {
        key: "self_control_axis",
        leftKey: "disciplined",
        leftLabel: "自律牽引",
        leftShort: "自律",
        leftStrength: "能為未來的自己先做安排",
        leftBlindSpot: "你有時會把鬆一下也看得太像失守",
        leftGrowth: "讓自律裡有空氣，通常更能長久",
        rightKey: "impulsive",
        rightLabel: "衝動牽引",
        rightShort: "衝動",
        rightStrength: "敢回應當下真實的渴望與情緒",
        rightBlindSpot: "你有時會把短暫舒服留給現在，把後果丟給之後",
        rightGrowth: "先接住那個想要，再替它找一個不必後悔的出口",
      },
      {
        key: "time_horizon_axis",
        leftKey: "long_term",
        leftLabel: "長期取向",
        leftShort: "長期",
        leftStrength: "願意為更遠的目標延遲滿足",
        leftBlindSpot: "你可能常常只記得應該，忘了自己也需要獎勵",
        leftGrowth: "讓長期感和當下回饋同時存在，你才不會一直靠硬撐",
        rightKey: "present_reward",
        rightLabel: "即時回饋取向",
        rightShort: "當下回饋",
        rightStrength: "對當下的身心訊號很敏感，不容易完全把自己耗乾",
        rightBlindSpot: "如果每次都先顧眼前，長期目標會很容易被稀釋",
        rightGrowth: "保留即時回饋，但替重要的長期方向設一個最小底線",
      },
    ],
    tagLabels: {
      restraint: "克制力",
      reward: "當下獎勵",
      fatigue: "疲累感",
      consistency: "連續性",
      temptation: "誘惑感",
      recovery: "回補需求",
    },
    profileTitles: {
      quadrant_ll: "長線執行者",
      quadrant_lr: "節制補氧者",
      quadrant_rl: "衝刺守目者",
      quadrant_rr: "當下回應者",
      balanced_integration: "節奏自管者",
      balanced_bridge: "彈性自律者",
      tension_mirror: "意志拉扯者",
      tension_pivot: "規則重寫者",
    },
    promptTemplates: [
      "當{context}時，你跟自己的拉扯通常最像哪一種？",
      "遇到{context}這種時刻，你多半怎麼跟慾望和目標談判？",
      "如果{context}，你最容易先做哪一步？",
      "在{context}的那一刻，你最在意被滿足的是什麼？",
    ],
    contexts: [
      "半夜很想再滑一下手機",
      "存錢計畫遇到一個你超喜歡的東西",
      "休息日一想到工作就想先躺著",
      "飲食或作息剛剛又有點失守",
      "眼前的任務很無聊，但很重要",
      "短期舒服和長期目標正面衝突",
      "你已經很累了，卻還有事情沒做完",
      "一個小誘惑突然出現在你面前",
    ],
    packs: [
      makePack([
        { text: "我會提醒自己先想遠一點，不想為了一時舒服打亂整體。", tags: { restraint: 1, consistency: 1 } },
        { text: "我會衡量一下，讓自己有點鬆又不至於完全偏掉。", tags: { restraint: 1, recovery: 1 } },
        { text: "我會先回應那股衝動，但心裡還是記得大方向。", tags: { temptation: 1, consistency: 1 } },
        { text: "我通常會先給自己當下想要的，之後再說。", tags: { reward: 1, fatigue: 1 } },
      ]),
      makePack([
        { text: "我會跟自己說先撐過這段，未來的我會謝謝現在。", tags: { restraint: 1, consistency: 1 } },
        { text: "我會想找一個不需要全忍、也不需要全放掉的方法。", tags: { recovery: 1, restraint: 1 } },
        { text: "我可能會先順著想做的感覺走，但不會完全忘記目標。", tags: { temptation: 1, consistency: 1 } },
        { text: "如果現在真的很想，我通常很難假裝自己不想。", tags: { reward: 1, fatigue: 1 } },
      ]),
      makePack([
        { text: "先守住最低限度，讓自己不要整段掉下去。", tags: { restraint: 1, consistency: 1 } },
        { text: "先做一點、休一點，讓我還能繼續和自己合作。", tags: { recovery: 1, restraint: 1 } },
        { text: "先順著衝勁做最有感的部分，再把其他補回來。", tags: { temptation: 1, consistency: 1 } },
        { text: "先滿足眼前，不然我根本沒心情談長期。", tags: { reward: 1, fatigue: 1 } },
      ]),
      makePack([
        { text: "我在意的是不要背叛長期想成為的自己。", tags: { restraint: 1, consistency: 1 } },
        { text: "我在意的是不要把自己逼到最後只剩反彈。", tags: { recovery: 1, fatigue: 1 } },
        { text: "我在意的是不要把現在活得太死，失去人味。", tags: { temptation: 1, reward: 1 } },
        { text: "我在意的是現在能不能先舒服一點、鬆一點。", tags: { reward: 1, fatigue: 1 } },
      ]),
    ],
  },
  {
    slug: "life-values",
    code: "LV",
    icon: "✶",
    title: "你的人生排序，最常被哪兩種價值拉扯？",
    shortTitle: "人生價值",
    subtitle: "你選擇事情的方式，透露你想把生命放在哪裡。",
    description: "從關係、自由、穩定與影響感的排序，看見你真正重視的是什麼。",
    cardDescription: "照出你更重視連結或自主、影響感或安全感。",
    heroCopy: "人生裡很多難題，本質上都在提醒我們重新排序價值。這份測驗想照出你到底想守住什麼、又願意為什麼冒險。",
    shareTitle: "人生價值心理測驗",
    shareDescription: "看見你在關係、自由、影響感與安全感之間最在乎的排序。",
    themeColor: "#6b7c57",
    themeColorSoft: "#d3dfc3",
    themeInk: "#182015",
    themeGlow: "rgba(107,124,87,0.27)",
    domain: "人生排序、投入方向與選擇代價",
    surpriseLine: "你願意守住的東西本來就有重量，這份重量讓你更懂取捨。",
    axes: [
      {
        key: "value_belonging_axis",
        leftKey: "connection",
        leftLabel: "關係與連結",
        leftShort: "連結",
        leftStrength: "把人與在乎放進人生的重要位置",
        leftBlindSpot: "你有時會為了不失去連結，而延後自己的真實需求",
        leftGrowth: "把連結留著，但不要把自己一起讓掉",
        rightKey: "autonomy",
        rightLabel: "自主與空間",
        rightShort: "自主",
        rightStrength: "知道自由度與主導權對你很重要",
        rightBlindSpot: "你可能在想保有自己時，也失去被支持的機會",
        rightGrowth: "讓自主和被陪伴一起存在",
      },
      {
        key: "value_security_axis",
        leftKey: "impact",
        leftLabel: "意義與影響",
        leftShort: "影響",
        leftStrength: "願意把生命投向有價值感的事",
        leftBlindSpot: "你有時會為了值得感而忽略現實成本",
        leftGrowth: "替理想加一點穩定的容器，影響力才撐得久",
        rightKey: "security",
        rightLabel: "穩定與安全",
        rightShort: "安全",
        rightStrength: "懂得照顧現實底盤，不讓自己一直活在驚險裡",
        rightBlindSpot: "你可能在過度保守時，錯過真的想要的人生感",
        rightGrowth: "讓安全感成為地板，支撐你做出更開闊的選擇",
      },
    ],
    tagLabels: {
      belonging: "歸屬感",
      independence: "自主感",
      purpose: "價值感",
      safety: "穩定需求",
      sacrifice: "取捨感",
      horizon: "人生視野",
    },
    profileTitles: {
      quadrant_ll: "關係使命者",
      quadrant_lr: "溫穩守護者",
      quadrant_rl: "自由理想者",
      quadrant_rr: "自主築底者",
      balanced_integration: "價值整合者",
      balanced_bridge: "人生調序者",
      tension_mirror: "排序拉扯者",
      tension_pivot: "方向重排者",
    },
    promptTemplates: [
      "當{context}時，你人生排序裡最先浮上來的通常是哪一種價值？",
      "遇到{context}這種選擇題，你多半怎麼跟自己的價值觀對話？",
      "如果{context}，你最容易先做哪一步？",
      "在{context}的那一刻，你最怕錯過的是什麼？",
    ],
    contexts: [
      "工作選擇和生活平衡必須取捨",
      "你在考慮要不要搬離熟悉環境",
      "你得在陪人和陪自己之間做安排",
      "一條路很穩，一條路很有野心",
      "你想做一件有意義但不算穩的事",
      "別人期待你優先照顧關係",
      "收入與自由度正在拉扯",
      "你開始重新思考人生到底想投資在哪裡",
    ],
    packs: [
      makePack([
        { text: "我會先想這個選擇會把我帶向誰、讓我和誰更靠近。", tags: { belonging: 1, purpose: 1 } },
        { text: "我會先想怎麼守住關係，同時不要把現實底盤弄掉。", tags: { belonging: 1, safety: 1 } },
        { text: "我會先問這件事有沒有更靠近我真正想活的樣子。", tags: { independence: 1, purpose: 1 } },
        { text: "我會先確定自己還能保有主導權和基本安全。", tags: { independence: 1, safety: 1 } },
      ]),
      makePack([
        { text: "我會先感受這件事能不能讓我和重要的人都更有意義。", tags: { belonging: 1, purpose: 1 } },
        { text: "我會想顧好連結，也顧好那份能安心過日子的底。", tags: { belonging: 1, safety: 1 } },
        { text: "我需要確認自己活得安全，也活得真。", tags: { independence: 1, purpose: 1 } },
        { text: "我會先讓自己站穩，再談更遠的理想。", tags: { independence: 1, safety: 1 } },
      ]),
      makePack([
        { text: "先看這條路能不能讓在乎與價值感同時存在。", tags: { belonging: 1, purpose: 1 } },
        { text: "先保住關係與生活底盤，不讓代價一下子太大。", tags: { belonging: 1, safety: 1 } },
        { text: "先靠近那個更像我想成為的自己的方向。", tags: { independence: 1, purpose: 1 } },
        { text: "先確保現實可持續，不想把人生變成一直在賭。", tags: { independence: 1, safety: 1 } },
      ]),
      makePack([
        { text: "我最怕錯過的是和重要的人、重要的事真正連上。", tags: { belonging: 1, purpose: 1 } },
        { text: "我最怕的是一個選擇讓我和在乎的生活一起失去穩定。", tags: { belonging: 1, safety: 1 } },
        { text: "我最怕的是活得很安全，卻越來越不像自己。", tags: { independence: 1, purpose: 1 } },
        { text: "我最怕的是理想很漂亮，但最後把自己耗到沒有底。", tags: { independence: 1, safety: 1 } },
      ]),
    ],
  },
];

export const QUIZ_TOPICS = THEME_BLUEPRINTS.map(buildTopic);

export function getQuizTopic(slug) {
  return QUIZ_TOPICS.find((topic) => topic.slug === slug) || null;
}

export function listQuizCards() {
  return QUIZ_TOPICS.map((topic) => ({
    slug: topic.slug,
    icon: topic.icon,
    title: topic.title,
    shortTitle: topic.shortTitle,
    subtitle: topic.subtitle,
    cardDescription: topic.cardDescription,
    themeColor: topic.themeColor,
    themeColorSoft: topic.themeColorSoft,
    themeInk: topic.themeInk,
    themeGlow: topic.themeGlow,
    questionPoolSize: topic.questionPoolSize,
    questionsPerSession: topic.questionsPerSession,
  }));
}
